<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data=array(
            array(
                'name'=>'Admin',
                'email'=>'admin@gmail.com',
                'password'=>Hash::make('admin'),
                'role'=>'admin',
                'status'=>'active'
            ),
            array(
                'name'=>'User1',
                'email'=>'user1@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'user',
                'status'=>'active'
            ),
            array(
                'name'=>'User2',
                'email'=>'user2@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'user',
                'status'=>'active'
            ),
            array(
                'name'=>'User3',
                'email'=>'user3@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'user',
                'status'=>'active'
            ),
            array(
                'name'=>'User4',
                'email'=>'user4@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'user',
                'status'=>'active'
            ),
            array(
                'name'=>'User5',
                'email'=>'user5@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'user',
                'status'=>'active'
            ),
            array(
                'name'=>'User6',
                'email'=>'user6@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'user',
                'status'=>'active'
            ),
            array(
                'name'=>'User7',
                'email'=>'user7@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'user',
                'status'=>'active'
            ),
            array(
                'name'=>'User8',
                'email'=>'user8@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'user',
                'status'=>'active'
            ),
            array(
                'name'=>'User9',
                'email'=>'user9@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'user',
                'status'=>'active'
            ),
            array(
                'name'=>'User10',
                'email'=>'user10@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'user',
                'status'=>'active'
            ),
            array(
                'name'=>'User11',
                'email'=>'user11@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'user',
                'status'=>'active'
            ),
            array(
                'name'=>'User12',
                'email'=>'user12@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'user',
                'status'=>'active'
            ),
            array(
                'name'=>'User13',
                'email'=>'user13@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'user',
                'status'=>'active'
            ),
            array(
                'name'=>'User14',
                'email'=>'user14@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'user',
                'status'=>'active'
            ),
            array(
                'name'=>'User15',
                'email'=>'user15@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'user',
                'status'=>'active'
            ),
            array(
                'name'=>'User16',
                'email'=>'user16@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'user',
                'status'=>'active'
            ),
            array(
                'name'=>'DG. SIDA',
                'email'=>'dgsida@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'pedagang',
                'status'=>'active'
            ),
            array(
                'name'=>'LINA',
                'email'=>'lina@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'pedagang',
                'status'=>'active'
            ),
            array(
                'name'=>'MARTA',
                'email'=>'marta@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'pedagang',
                'status'=>'active'
            ),
            array(
                'name'=>'DG. NARTI',
                'email'=>'dgnarti@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'pedagang',
                'status'=>'active'
            ),
            array(
                'name'=>'SUPARDI',
                'email'=>'supardi@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'pedagang',
                'status'=>'active'
            ),
            array(
                'name'=>'DG. SARNI',
                'email'=>'dgsarni@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'pedagang',
                'status'=>'active'
            ),
            array(
                'name'=>'DG. ATI',
                'email'=>'dgati@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'pedagang',
                'status'=>'active'
            ),
            array(
                'name'=>'ARMAN',
                'email'=>'arman@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'pedagang',
                'status'=>'active'
            ),
            array(
                'name'=>'ARIF',
                'email'=>'arif@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'pedagang',
                'status'=>'active'
            ),
            array(
                'name'=>'DG. INTANG',
                'email'=>'dgintang@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'pedagang',
                'status'=>'active'
            ),
            array(
                'name'=>'BANI',
                'email'=>'bani@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'nelayan',
                'status'=>'active'
            ),
            array(
                'name'=>'IMRAN',
                'email'=>'imran@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'nelayan',
                'status'=>'active'
            ),
            array(
                'name'=>'RAHMAT',
                'email'=>'rahmat@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'nelayan',
                'status'=>'active'
            ),
            array(
                'name'=>'FARHAN',
                'email'=>'farhan@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'nelayan',
                'status'=>'active'
            ),
            array(
                'name'=>'RISAL',
                'email'=>'risal@gmail.com',
                'password'=>Hash::make('12345'),
                'role'=>'nelayan',
                'status'=>'active'
            ),
        );

        DB::table('users')->insert($data);
    }
}
